In [1]:
# Order of creation operators acting on vaccum state matters (set a format/rule)
# Create dictionary for string of numbers containing all basis states
# Hamiltonian will have size dim(Dictionary)**2
# N_particles, total Energy, lepton flavor (if vacuum mixing is off), and 3-momentum are conserved
# Check difference between KE conserved and unconserved (without diagonalizing H, should be easy to tell)
# Particle (center of radius) vs beam (beam of size radius)

# Beam is homogeneous, particle can be either

In [1]:
import numpy as np
from itertools import combinations
from math import comb

In [2]:
filename = 'fourmax_four'
pmax = 4

In [3]:
dp = 1.0
pmin = -pmax
np1 = round((pmax-pmin)/dp) + 1
np1 #max number of momentum modes in 1-dimension

9

In [4]:
ps_grid = np.zeros((np1**2,3))
pxs, pys = np.meshgrid(np.linspace(pmin,pmax,np1), np.linspace(pmin,pmax,np1))
ps_grid[:,0] = pxs.reshape(np1**2)
ps_grid[:,1] = pys.reshape(np1**2)
ps_grid[:,2] = np.zeros(np1**2)
ps_grid #grid of all momentum modes within range of [pmin, pmax]

array([[-4., -4.,  0.],
       [-3., -4.,  0.],
       [-2., -4.,  0.],
       [-1., -4.,  0.],
       [ 0., -4.,  0.],
       [ 1., -4.,  0.],
       [ 2., -4.,  0.],
       [ 3., -4.,  0.],
       [ 4., -4.,  0.],
       [-4., -3.,  0.],
       [-3., -3.,  0.],
       [-2., -3.,  0.],
       [-1., -3.,  0.],
       [ 0., -3.,  0.],
       [ 1., -3.,  0.],
       [ 2., -3.,  0.],
       [ 3., -3.,  0.],
       [ 4., -3.,  0.],
       [-4., -2.,  0.],
       [-3., -2.,  0.],
       [-2., -2.,  0.],
       [-1., -2.,  0.],
       [ 0., -2.,  0.],
       [ 1., -2.,  0.],
       [ 2., -2.,  0.],
       [ 3., -2.,  0.],
       [ 4., -2.,  0.],
       [-4., -1.,  0.],
       [-3., -1.,  0.],
       [-2., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [ 1., -1.,  0.],
       [ 2., -1.,  0.],
       [ 3., -1.,  0.],
       [ 4., -1.,  0.],
       [-4.,  0.,  0.],
       [-3.,  0.,  0.],
       [-2.,  0.,  0.],
       [-1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.

In [5]:
kes_grid = np.zeros(np1**2)
kes_grid = np.sqrt(ps_grid[:,0]**2+ps_grid[:,1]**2+ps_grid[:,2]**2)
kes_grid # grid of all potential energies (associated with each momentum mode)

array([5.65685425, 5.        , 4.47213595, 4.12310563, 4.        ,
       4.12310563, 4.47213595, 5.        , 5.65685425, 5.        ,
       4.24264069, 3.60555128, 3.16227766, 3.        , 3.16227766,
       3.60555128, 4.24264069, 5.        , 4.47213595, 3.60555128,
       2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712,
       3.60555128, 4.47213595, 4.12310563, 3.16227766, 2.23606798,
       1.41421356, 1.        , 1.41421356, 2.23606798, 3.16227766,
       4.12310563, 4.        , 3.        , 2.        , 1.        ,
       0.        , 1.        , 2.        , 3.        , 4.        ,
       4.12310563, 3.16227766, 2.23606798, 1.41421356, 1.        ,
       1.41421356, 2.23606798, 3.16227766, 4.12310563, 4.47213595,
       3.60555128, 2.82842712, 2.23606798, 2.        , 2.23606798,
       2.82842712, 3.60555128, 4.47213595, 5.        , 4.24264069,
       3.60555128, 3.16227766, 3.        , 3.16227766, 3.60555128,
       4.24264069, 5.        , 5.65685425, 5.        , 4.47213

In [6]:
# ps = []
# kes = []

# # Impose ke < pmax
# for i in range(len(kes_grid)):
#     if kes_grid[i] < pmax+1e-5 and kes_grid[i] > 0 and ps_grid[i,0] >  0: #if all kin. energies are nonzero, within our circle defined by 
#         ps.append(ps_grid[i])                                             #pmax and x coordinate of momentum is positive (for semicircle)
#         kes.append(kes_grid[i])

# np2 = len(kes) #number of momentum modes in 2-dimensions
# ps = np.array(ps)
# kes = np.array(kes)

# ps, kes #all momentum modes and corresponding KEs within range


ps = []
kes = []
ps_str = []

# Impose ke < pmax
for i in range(len(kes_grid)):
    if kes_grid[i] < pmax+1e-5 and kes_grid[i] > 0: #if all kin. energies are nonzero and within our circle defined by pmax 
        ps.append(ps_grid[i])  
        ps_str.append(str(ps_grid[i]))                                           
        kes.append(kes_grid[i])

np2 = len(kes) #number of momentum modes in 2-dimensions
ps = np.array(ps)
kes = np.array(kes)

ps, kes #all momentum modes and corresponding KEs within range

(array([[ 0., -4.,  0.],
        [-2., -3.,  0.],
        [-1., -3.,  0.],
        [ 0., -3.,  0.],
        [ 1., -3.,  0.],
        [ 2., -3.,  0.],
        [-3., -2.,  0.],
        [-2., -2.,  0.],
        [-1., -2.,  0.],
        [ 0., -2.,  0.],
        [ 1., -2.,  0.],
        [ 2., -2.,  0.],
        [ 3., -2.,  0.],
        [-3., -1.,  0.],
        [-2., -1.,  0.],
        [-1., -1.,  0.],
        [ 0., -1.,  0.],
        [ 1., -1.,  0.],
        [ 2., -1.,  0.],
        [ 3., -1.,  0.],
        [-4.,  0.,  0.],
        [-3.,  0.,  0.],
        [-2.,  0.,  0.],
        [-1.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 2.,  0.,  0.],
        [ 3.,  0.,  0.],
        [ 4.,  0.,  0.],
        [-3.,  1.,  0.],
        [-2.,  1.,  0.],
        [-1.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  1.,  0.],
        [ 2.,  1.,  0.],
        [ 3.,  1.,  0.],
        [-3.,  2.,  0.],
        [-2.,  2.,  0.],
        [-1.,  2.,  0.],
        [ 0.,  2.,  0.],
        [ 1.,  2.,  0.],


In [7]:
print(f'Number of momentum modes: {np2}')
print('Momentum modes:')
for i in range(np2):
    print(i, ps[i,:])

Number of momentum modes: 48
Momentum modes:
0 [ 0. -4.  0.]
1 [-2. -3.  0.]
2 [-1. -3.  0.]
3 [ 0. -3.  0.]
4 [ 1. -3.  0.]
5 [ 2. -3.  0.]
6 [-3. -2.  0.]
7 [-2. -2.  0.]
8 [-1. -2.  0.]
9 [ 0. -2.  0.]
10 [ 1. -2.  0.]
11 [ 2. -2.  0.]
12 [ 3. -2.  0.]
13 [-3. -1.  0.]
14 [-2. -1.  0.]
15 [-1. -1.  0.]
16 [ 0. -1.  0.]
17 [ 1. -1.  0.]
18 [ 2. -1.  0.]
19 [ 3. -1.  0.]
20 [-4.  0.  0.]
21 [-3.  0.  0.]
22 [-2.  0.  0.]
23 [-1.  0.  0.]
24 [1. 0. 0.]
25 [2. 0. 0.]
26 [3. 0. 0.]
27 [4. 0. 0.]
28 [-3.  1.  0.]
29 [-2.  1.  0.]
30 [-1.  1.  0.]
31 [0. 1. 0.]
32 [1. 1. 0.]
33 [2. 1. 0.]
34 [3. 1. 0.]
35 [-3.  2.  0.]
36 [-2.  2.  0.]
37 [-1.  2.  0.]
38 [0. 2. 0.]
39 [1. 2. 0.]
40 [2. 2. 0.]
41 [3. 2. 0.]
42 [-2.  3.  0.]
43 [-1.  3.  0.]
44 [0. 3. 0.]
45 [1. 3. 0.]
46 [2. 3. 0.]
47 [0. 4. 0.]


In [8]:
# Input is 3-dim momentum, returns |p|, theta and phi (0-2pi)
def p_spherical(p):
    absp = np.sqrt(np.sum(p*p))
    theta = np.arctan2(np.sqrt(p[0]**2+p[1]**2), p[2])
    phi = np.arctan2(p[1],p[0])
    return absp, theta, phi

# g factor for H_vv
def g_factor(p1, p2, q1, q2):
    absp1, tp1, pp1 = p_spherical(p1)
    absp2, tp2, pp2 = p_spherical(p2)
    absq1, tq1, pq1 = p_spherical(q1)
    absq2, tq2, pq2 = p_spherical(q2)
    fac1 = np.exp(-1j*pq1)*np.sin(tq1/2.)*np.cos(tq2/2.) - np.exp(-1j*pq2)*np.cos(tq1/2.)*np.sin(tq2/2.)
    fac2 = np.exp(1j*pp1)*np.sin(tp1/2.)*np.cos(tp2/2.) - np.exp(1j*pp2)*np.cos(tp1/2.)*np.sin(tp2/2.)
    return 2 * fac1 * fac2

In [ ]:
# kec_nt = [] #all possible states with KE NOT conserved

# for i1 in range(np2):
#     p1 = ps[i1,:]
#     for i2 in range(i1,np2):
#         p2 = ps[i2,:]
#         for i3 in range(np2):
#             p3 = ps[i3,:]
#             for i4 in range(i3,np2):
#                 p4 = ps[i4,:]
#                 pdiff = p1+p2-p3-p4
#                 if np.sum(np.abs(pdiff)) < 1e-7:
#                     gf = g_factor(p1,p2,p3,p4)
#                     if np.abs(gf) > 1e-7:
#                         if i1!=i3:
#                             kec_nt.append([i1,i2,i3,i4])

# kec_nt = np.array(kec_nt) 
# Nkec = len(kec_nt)      #All sets of conserved p

#Nkec, kec_nt

In [ ]:
kec_nt = [] #all possible states with KE conserved

for i1 in range(np2):
    p1 = ps[i1,:]
    for i2 in range(i1,np2):
        p2 = ps[i2,:]
        for i3 in range(np2):
            p3 = ps[i3,:]
            p4 =  p1+p2-p3
            p4_mag = np.linalg.norm(p4)
            if p4_mag <= pmax and p4_mag != 0:
                i4 = ps_str.index(str(p4))
                if i1!=i3 and i4>i3:
                    gfactor = g_factor(p1,p2,p3,p4)
                    if np.abs(gfactor) > 1e-7: #ensuring only appending terms where g>0
                        kec_nt.append([i1,i2,i3,i4])

kec_nt = np.array(kec_nt) 
Nkec = len(kec_nt)      #All sets of conserved KE

Nkec, kec_nt

In [66]:
for s in kec_nt:
    print(s)

[0 6 1 3]
[0 7 1 4]
[0 7 2 3]
[0 9 2 5]
[0 9 3 4]
[ 0 10  3  5]
[ 0 11  2  6]
[ 0 12  1  8]
[ 0 12  2  7]
[ 0 12  3  6]
[ 0 13  1  9]
[ 0 13  2  8]
[ 0 13  3  7]
[ 0 13  4  6]
[ 0 14  2 10]
[ 0 14  3  9]
[ 0 14  4  8]
[ 0 14  5  7]
[ 0 15  3 10]
[ 0 15  4  9]
[ 0 15  5  8]
[ 0 16  4 10]
[ 0 17  2 13]
[ 0 17  3 12]
[ 0 17  4 11]
[ 0 17  6  8]
[ 0 18  1 14]
[ 0 18  3 13]
[ 0 18  4 12]
[ 0 18  5 11]
[ 0 18  6  9]
[ 0 18  7  8]
[ 0 19  1 15]
[ 0 19  2 14]
[ 0 19  4 13]
[ 0 19  5 12]
[ 0 19  6 10]
[ 0 19  7  9]
[ 0 20  1 16]
[ 0 20  2 15]
[ 0 20  3 14]
[ 0 20  5 13]
[ 0 20  7 10]
[ 0 20  8  9]
[ 0 21  2 16]
[ 0 21  3 15]
[ 0 21  4 14]
[ 0 21  8 10]
[ 0 22  1 19]
[ 0 22  2 18]
[ 0 22  3 17]
[ 0 22  7 13]
[ 0 22  8 12]
[ 0 22  9 11]
[ 0 23  1 20]
[ 0 23  2 19]
[ 0 23  3 18]
[ 0 23  4 17]
[ 0 23  6 14]
[ 0 23  8 13]
[ 0 23  9 12]
[ 0 23 10 11]
[ 0 24  1 21]
[ 0 24  2 20]
[ 0 24  3 19]
[ 0 24  4 18]
[ 0 24  5 17]
[ 0 24  6 15]
[ 0 24  7 14]
[ 0 24  9 13]
[ 0 24 10 12]
[ 0 25  2 21]
[ 0 25  3 20

In [63]:
Nkec

1798

In [27]:
# reference state
ninit = np.sort(np.array([11, 12, 13, 15]))
# ninit = np.sort(np.array([20, 21, 22, 23, 26]))
# ninit = np.sort(np.array([4, 5, 7]))
Ne = 1                            #number of electron neutrinos in initial state

Nn = len(ninit)                   #number of neutrinos
Nm = Nn - Ne                      #number of muon neutrinos

pinit = np.sum(ps[ninit], axis=0) #total momentum of initial state
keinit = np.sum(kes[ninit])       #KE of initial state
print(f'Reference state is {ninit}')
print(f'Reference state total momentum: {pinit}')
print(f'Reference state kinetic energy: {keinit}')

Reference state is [11 12 13 15]
Reference state total momentum: [-4.  0.  0.]
Reference state kinetic energy: 8.0


In [28]:
# Write momentum modes and other initial settings to 'filename'_p.dat file
g =  open(filename+'_p.dat', 'w')
g.write(f'# dp = {dp}' + '\n')
g.write(f'# pmax = {pmax}' + '\n')
g.write(f'# Initial state is {ninit}' + '\n')
g.write(f'# Initial number of electron neutrinos: {Ne}' + '\n')
g.write(f'# Initial total momentum: {pinit}' + '\n')
g.write(f'# Initial kinetic energy: {keinit}' + '\n')
g.write(f'# Number of momentum modes: {np2}' + '\n')
# Write pairs of momentum modes which conserve P and KE
for i in range(len(kec_nt)):
    gfac = g_factor(ps[kec_nt[i,0],:],ps[kec_nt[i,1],:],ps[kec_nt[i,2],:],ps[kec_nt[i,3],:])
    g.write(f'# {kec_nt[i,0]} {kec_nt[i,1]} --- {kec_nt[i,2]} {kec_nt[i,3]}: {np.abs(gfac)}' + '\n')
# Write momentum modes
for i in range(len(ps)):
    g.write(f'{ps[i,0]} {ps[i,1]} {ps[i,2]}' + '\n')

In [29]:
binom = np.array(list(combinations([i for i in range(Nn)],2)))
Nbinom = len(binom)
binom

array([[0, 1],
       [0, 2],
       [0, 3],
       [1, 2],
       [1, 3],
       [2, 3]])

In [30]:
# Check if the same momentum mode is used only up to twice
def check(state):
    ans = True
    for i in range(len(state)-2):
        if np.var(state[i:i+3]) < 1e-7:
            ans = False
    return ans

In [31]:
# For a given pair of Nn momentum modes, return the pairs that Hvv can take to
def apply(state):
    newstate = []
    for i in range(Nbinom):
        k = np.array([state[binom[i,0]], state[binom[i,1]]])
        for j in range(Nkec):
            if np.sum(np.abs(k-kec_nt[j,:2]))==0:
                state_i = state.copy()
                state_i[binom[i,0]] = kec_nt[j,2]
                state_i[binom[i,1]] = kec_nt[j,3]
                state_i = np.sort(state_i)
                if check(state_i):
                    newstate.append(state_i)
    return np.array(newstate)

In [32]:
nnewstate = 10  # > 1 to enter the while loop
p_states = np.array([ninit])
newstate1 = np.array([np.zeros(Nn), ninit])
trial = 0

start = time.time()

while nnewstate > 1:
    print(f'---------------- H^{trial+1} ----------------')
    newstate2 = np.zeros((1,Nn))
    #newstate3 = np.zeros((1,Nn))
    for i in range(1,len(newstate1)):
        newi = apply(newstate1[i])
        if len(newi) > 0:
            newstate2 = np.append(newstate2, newi, axis=0)
       
    newstate1 = np.array([np.zeros(Nn)])
    for j in range(1,len(newstate2)):
        dist = np.sum(np.abs(p_states - newstate2[j]), axis=1)
        if np.min(dist) > 1e-7:
            p_states = np.append(p_states, [newstate2[j].astype(int)], axis=0)
            newstate1 = np.append(newstate1, [newstate2[j]], axis=0)
    nnewstate = len(newstate1)
    print(f'Number of new states(mod flavor choice) at this round: {nnewstate-1}')
    print(f'Number of states(mod flavor choice) visited so far: {len(p_states)}')
        
    trial += 1
end = time.time()
print('#########################')
print('Finished listing all basis states (mod flavor choice) connected to the reference state')
print(f'Took {end- start} seconds')

---------------- H^1 ----------------
Number of new states(mod flavor choice) at this round: 31
Number of states(mod flavor choice) visited so far: 32
---------------- H^2 ----------------
Number of new states(mod flavor choice) at this round: 111
Number of states(mod flavor choice) visited so far: 143
---------------- H^3 ----------------
Number of new states(mod flavor choice) at this round: 84
Number of states(mod flavor choice) visited so far: 227
---------------- H^4 ----------------
Number of new states(mod flavor choice) at this round: 0
Number of states(mod flavor choice) visited so far: 227
#########################
Finished listing all basis states (mod flavor choice) connected to the reference state
Took 19.485185861587524 seconds


In [18]:
n_states = 0
skipped = 0                     #number of unviable states

# Write all basis states visited to 'filename'_s.dat file.
with open(filename + '_s.dat', 'w') as f:    
    for i in range(len(p_states)):
        totp = np.sum(ps[p_states[i]], axis=0)
        totke = np.sum(kes[p_states[i]])
        Nrp = Nn-len(set(p_states[i]))

        if Nn-2*Nrp >= 0 and Ne-Nrp >= 0:
            nstate = comb(Nn-2*Nrp, Ne-Nrp)
            #nstate = 2**Nn/4**(Nn-len(set(p_states[i]))) #NON-FLAVOR DEPENDENT
            strs = ' '.join([str(x) for x in p_states[i]]) + '\n'
            f.write(strs)
            n_states += nstate
            # if np.sum(np.abs(totp-pinit)) > 1e-7 or np.abs(totke-keinit) > 1e-7:
            #     print('Total momentum or kinetic energy is not conserved!')
        else:
            skipped += 1


print(f'Number of momentum modes pair with conserved P and E is {len(p_states)-skipped}')
print(f'Number of states with conserved P, E, and flavor content is {n_states:.0f}')
bins_visited = np.sort(np.array(list(set(p_states.flatten()))))
print(f'Activated momentum modes:')
print(bins_visited)


# #g.write(f'# bins visited: {bins_visited}'+'\n')
# g.write(f'# Number of basis states with conserved P, E, and flavor content is {n_states:.0f}')
# g.close()

Number of momentum modes pair with conserved P and E is 11
Number of states with conserved P, E, and flavor content is 31
Activated momentum modes:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
